namespace ComputerClubWinForms.Forms
{
    partial class SessionPage
    {
        private System.ComponentModel.IContainer? components = null;
        private System.Windows.Forms.Timer refreshTimer = null!;
        private System.Windows.Forms.TableLayoutPanel mainLayout = null!;
        private System.Windows.Forms.GroupBox clientPanel = null!;
        private System.Windows.Forms.TextBox txtClientSearch = null!;
        private System.Windows.Forms.DataGridView gridClients = null!;
        private System.Windows.Forms.GroupBox hallGroup = null!;
        private System.Windows.Forms.FlowLayoutPanel hallPanel = null!;
        private System.Windows.Forms.Label lblSelectedComputer = null!;
        private System.Windows.Forms.Panel actionsPanel = null!;
        private System.Windows.Forms.Button btnStart = null!;
        private System.Windows.Forms.Button btnBooking = null!;
        private System.Windows.Forms.Button btnStartBooking = null!;
        private System.Windows.Forms.Button btnExtend = null!;
        private System.Windows.Forms.Button btnComplete = null!;
        private System.Windows.Forms.Button btnDeleteBooking = null!;
        private System.Windows.Forms.Button btnRefresh = null!;
        private System.Windows.Forms.GroupBox sessionsGroup = null!;
        private System.Windows.Forms.DataGridView gridSessions = null!;
        private System.Windows.Forms.GroupBox bookingsGroup = null!;
        private System.Windows.Forms.DataGridView gridBookings = null!;
        private System.Windows.Forms.Label lblMessage = null!;
        private System.Windows.Forms.Button btnHall1 = null!;
        private System.Windows.Forms.Button btnHall2 = null!;
        private System.Windows.Forms.Button btnHall3 = null!;
        private System.Windows.Forms.Button btnHall4 = null!;
        private System.Windows.Forms.Button btnHall5 = null!;
        private System.Windows.Forms.Button btnHall6 = null!;
        private System.Windows.Forms.Button btnHall7 = null!;
        private System.Windows.Forms.Button btnHall8 = null!;
        private System.Windows.Forms.Button btnHall9 = null!;
        private System.Windows.Forms.Button btnHall10 = null!;
        private System.Windows.Forms.Button btnHall11 = null!;
        private System.Windows.Forms.Button btnHall12 = null!;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.refreshTimer = new System.Windows.Forms.Timer(this.components);
            this.mainLayout = new System.Windows.Forms.TableLayoutPanel();
            this.clientPanel = new System.Windows.Forms.GroupBox();
            this.txtClientSearch = new System.Windows.Forms.TextBox();
            this.gridClients = new System.Windows.Forms.DataGridView();
            this.hallGroup = new System.Windows.Forms.GroupBox();
            this.hallPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.lblSelectedComputer = new System.Windows.Forms.Label();
            this.actionsPanel = new System.Windows.Forms.Panel();
            this.btnStart = new System.Windows.Forms.Button();
            this.btnBooking = new System.Windows.Forms.Button();
            this.btnStartBooking = new System.Windows.Forms.Button();
            this.btnExtend = new System.Windows.Forms.Button();
            this.btnComplete = new System.Windows.Forms.Button();
            this.btnDeleteBooking = new System.Windows.Forms.Button();
            this.btnRefresh = new System.Windows.Forms.Button();
            this.sessionsGroup = new System.Windows.Forms.GroupBox();
            this.gridSessions = new System.Windows.Forms.DataGridView();
            this.bookingsGroup = new System.Windows.Forms.GroupBox();
            this.gridBookings = new System.Windows.Forms.DataGridView();
            this.lblMessage = new System.Windows.Forms.Label();
            this.btnHall1 = new System.Windows.Forms.Button();
            this.btnHall2 = new System.Windows.Forms.Button();
            this.btnHall3 = new System.Windows.Forms.Button();
            this.btnHall4 = new System.Windows.Forms.Button();
            this.btnHall5 = new System.Windows.Forms.Button();
            this.btnHall6 = new System.Windows.Forms.Button();
            this.btnHall7 = new System.Windows.Forms.Button();
            this.btnHall8 = new System.Windows.Forms.Button();
            this.btnHall9 = new System.Windows.Forms.Button();
            this.btnHall10 = new System.Windows.Forms.Button();
            this.btnHall11 = new System.Windows.Forms.Button();
            this.btnHall12 = new System.Windows.Forms.Button();
            this.mainLayout.SuspendLayout();
            this.clientPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridClients)).BeginInit();
            this.hallGroup.SuspendLayout();
            this.hallPanel.SuspendLayout();
            this.actionsPanel.SuspendLayout();
            this.sessionsGroup.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridSessions)).BeginInit();
            this.bookingsGroup.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridBookings)).BeginInit();
            this.SuspendLayout();
            this.refreshTimer.Interval = 1000;
            this.refreshTimer.Tick += new System.EventHandler(this.OnTimerTick);
            this.mainLayout.ColumnCount = 2;
            this.mainLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 45F));
            this.mainLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 55F));
            this.mainLayout.Controls.Add(this.clientPanel, 0, 0);
            this.mainLayout.Controls.Add(this.hallGroup, 1, 0);
            this.mainLayout.Controls.Add(this.actionsPanel, 0, 1);
            this.mainLayout.Controls.Add(this.sessionsGroup, 0, 2);
            this.mainLayout.Controls.Add(this.bookingsGroup, 1, 2);
            this.mainLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mainLayout.Location = new System.Drawing.Point(0, 0);
            this.mainLayout.Name = "mainLayout";
            this.mainLayout.RowCount = 3;
            this.mainLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 38F));
            this.mainLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.mainLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 62F));
            this.mainLayout.Size = new System.Drawing.Size(1000, 568);
            this.mainLayout.TabIndex = 0;
            this.mainLayout.SetColumnSpan(this.actionsPanel, 2);
            this.clientPanel.Controls.Add(this.gridClients);
            this.clientPanel.Controls.Add(this.txtClientSearch);
            this.clientPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.clientPanel.Location = new System.Drawing.Point(3, 3);
            this.clientPanel.Name = "clientPanel";
            this.clientPanel.Size = new System.Drawing.Size(444, 183);
            this.clientPanel.TabIndex = 0;
            this.clientPanel.TabStop = false;
            this.clientPanel.Text = "Клиенты";
            this.txtClientSearch.Dock = System.Windows.Forms.DockStyle.Top;
            this.txtClientSearch.Location = new System.Drawing.Point(3, 21);
            this.txtClientSearch.Name = "txtClientSearch";
            this.txtClientSearch.PlaceholderText = "Поиск клиента";
            this.txtClientSearch.Size = new System.Drawing.Size(438, 25);
            this.txtClientSearch.TabIndex = 0;
            this.txtClientSearch.TextChanged += new System.EventHandler(this.OnClientSearchChanged);
            this.gridClients.AllowUserToAddRows = false;
            this.gridClients.AllowUserToDeleteRows = false;
            this.gridClients.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.gridClients.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gridClients.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridClients.Location = new System.Drawing.Point(3, 46);
            this.gridClients.MultiSelect = false;
            this.gridClients.Name = "gridClients";
            this.gridClients.ReadOnly = true;
            this.gridClients.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.gridClients.Size = new System.Drawing.Size(438, 134);
            this.gridClients.TabIndex = 1;
            this.hallGroup.Controls.Add(this.hallPanel);
            this.hallGroup.Controls.Add(this.lblSelectedComputer);
            this.hallGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.hallGroup.Location = new System.Drawing.Point(453, 3);
            this.hallGroup.Name = "hallGroup";
            this.hallGroup.Size = new System.Drawing.Size(544, 183);
            this.hallGroup.TabIndex = 1;
            this.hallGroup.TabStop = false;
            this.hallGroup.Text = "Схема зала";
            this.hallPanel.Controls.Add(this.btnHall1);
            this.hallPanel.Controls.Add(this.btnHall2);
            this.hallPanel.Controls.Add(this.btnHall3);
            this.hallPanel.Controls.Add(this.btnHall4);
            this.hallPanel.Controls.Add(this.btnHall5);
            this.hallPanel.Controls.Add(this.btnHall6);
            this.hallPanel.Controls.Add(this.btnHall7);
            this.hallPanel.Controls.Add(this.btnHall8);
            this.hallPanel.Controls.Add(this.btnHall9);
            this.hallPanel.Controls.Add(this.btnHall10);
            this.hallPanel.Controls.Add(this.btnHall11);
            this.hallPanel.Controls.Add(this.btnHall12);
            this.hallPanel.AutoScroll = true;
            this.hallPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.hallPanel.Location = new System.Drawing.Point(3, 21);
            this.hallPanel.Name = "hallPanel";
            this.hallPanel.Padding = new System.Windows.Forms.Padding(10);
            this.hallPanel.Size = new System.Drawing.Size(538, 127);
            this.hallPanel.TabIndex = 0;
            this.btnHall1.BackColor = System.Drawing.Color.FromArgb(210, 245, 215);
            this.btnHall1.Location = new System.Drawing.Point(10, 10);
            this.btnHall1.Margin = new System.Windows.Forms.Padding(10);
            this.btnHall1.Name = "btnHall1";
            this.btnHall1.Size = new System.Drawing.Size(96, 52);
            this.btnHall1.TabIndex = 0;
            this.btnHall1.Tag = 1;
            this.btnHall1.Text = "ПК 1";
            this.btnHall1.UseVisualStyleBackColor = false;
            this.btnHall2.BackColor = System.Drawing.Color.FromArgb(210, 245, 215);
            this.btnHall2.Location = new System.Drawing.Point(10, 10);
            this.btnHall2.Margin = new System.Windows.Forms.Padding(10);
            this.btnHall2.Name = "btnHall2";
            this.btnHall2.Size = new System.Drawing.Size(96, 52);
            this.btnHall2.TabIndex = 1;
            this.btnHall2.Tag = 2;
            this.btnHall2.Text = "ПК 2";
            this.btnHall2.UseVisualStyleBackColor = false;
            this.btnHall3.BackColor = System.Drawing.Color.FromArgb(210, 245, 215);
            this.btnHall3.Location = new System.Drawing.Point(10, 10);
            this.btnHall3.Margin = new System.Windows.Forms.Padding(10);
            this.btnHall3.Name = "btnHall3";
            this.btnHall3.Size = new System.Drawing.Size(96, 52);
            this.btnHall3.TabIndex = 2;
            this.btnHall3.Tag = 3;
            this.btnHall3.Text = "ПК 3";
            this.btnHall3.UseVisualStyleBackColor = false;
            this.btnHall4.BackColor = System.Drawing.Color.FromArgb(210, 245, 215);
            this.btnHall4.Location = new System.Drawing.Point(10, 10);
            this.btnHall4.Margin = new System.Windows.Forms.Padding(10);
            this.btnHall4.Name = "btnHall4";
            this.btnHall4.Size = new System.Drawing.Size(96, 52);
            this.btnHall4.TabIndex = 3;
            this.btnHall4.Tag = 4;
            this.btnHall4.Text = "ПК 4";
            this.btnHall4.UseVisualStyleBackColor = false;
            this.btnHall5.BackColor = System.Drawing.Color.FromArgb(210, 245, 215);
            this.btnHall5.Location = new System.Drawing.Point(10, 10);
            this.btnHall5.Margin = new System.Windows.Forms.Padding(10);
            this.btnHall5.Name = "btnHall5";
            this.btnHall5.Size = new System.Drawing.Size(96, 52);
            this.btnHall5.TabIndex = 4;
            this.btnHall5.Tag = 5;
            this.btnHall5.Text = "ПК 5";
            this.btnHall5.UseVisualStyleBackColor = false;
            this.btnHall6.BackColor = System.Drawing.Color.FromArgb(210, 245, 215);
            this.btnHall6.Location = new System.Drawing.Point(10, 10);
            this.btnHall6.Margin = new System.Windows.Forms.Padding(10);
            this.btnHall6.Name = "btnHall6";
            this.btnHall6.Size = new System.Drawing.Size(96, 52);
            this.btnHall6.TabIndex = 5;
            this.btnHall6.Tag = 6;
            this.btnHall6.Text = "ПК 6";
            this.btnHall6.UseVisualStyleBackColor = false;
            this.btnHall7.BackColor = System.Drawing.Color.FromArgb(210, 245, 215);
            this.btnHall7.Location = new System.Drawing.Point(10, 10);
            this.btnHall7.Margin = new System.Windows.Forms.Padding(10);
            this.btnHall7.Name = "btnHall7";
            this.btnHall7.Size = new System.Drawing.Size(96, 52);
            this.btnHall7.TabIndex = 6;
            this.btnHall7.Tag = 7;
            this.btnHall7.Text = "ПК 7";
            this.btnHall7.UseVisualStyleBackColor = false;
            this.btnHall8.BackColor = System.Drawing.Color.FromArgb(210, 245, 215);
            this.btnHall8.Location = new System.Drawing.Point(10, 10);
            this.btnHall8.Margin = new System.Windows.Forms.Padding(10);
            this.btnHall8.Name = "btnHall8";
            this.btnHall8.Size = new System.Drawing.Size(96, 52);
            this.btnHall8.TabIndex = 7;
            this.btnHall8.Tag = 8;
            this.btnHall8.Text = "ПК 8";
            this.btnHall8.UseVisualStyleBackColor = false;
            this.btnHall9.BackColor = System.Drawing.Color.FromArgb(210, 245, 215);
            this.btnHall9.Location = new System.Drawing.Point(10, 10);
            this.btnHall9.Margin = new System.Windows.Forms.Padding(10);
            this.btnHall9.Name = "btnHall9";
            this.btnHall9.Size = new System.Drawing.Size(96, 52);
            this.btnHall9.TabIndex = 8;
            this.btnHall9.Tag = 9;
            this.btnHall9.Text = "ПК 9";
            this.btnHall9.UseVisualStyleBackColor = false;
            this.btnHall10.BackColor = System.Drawing.Color.FromArgb(210, 245, 215);
            this.btnHall10.Location = new System.Drawing.Point(10, 10);
            this.btnHall10.Margin = new System.Windows.Forms.Padding(10);
            this.btnHall10.Name = "btnHall10";
            this.btnHall10.Size = new System.Drawing.Size(96, 52);
            this.btnHall10.TabIndex = 9;
            this.btnHall10.Tag = 10;
            this.btnHall10.Text = "ПК 10";
            this.btnHall10.UseVisualStyleBackColor = false;
            this.btnHall11.BackColor = System.Drawing.Color.FromArgb(210, 245, 215);
            this.btnHall11.Location = new System.Drawing.Point(10, 10);
            this.btnHall11.Margin = new System.Windows.Forms.Padding(10);
            this.btnHall11.Name = "btnHall11";
            this.btnHall11.Size = new System.Drawing.Size(96, 52);
            this.btnHall11.TabIndex = 10;
            this.btnHall11.Tag = 11;
            this.btnHall11.Text = "ПК 11";
            this.btnHall11.UseVisualStyleBackColor = false;
            this.btnHall12.BackColor = System.Drawing.Color.FromArgb(210, 245, 215);
            this.btnHall12.Location = new System.Drawing.Point(10, 10);
            this.btnHall12.Margin = new System.Windows.Forms.Padding(10);
            this.btnHall12.Name = "btnHall12";
            this.btnHall12.Size = new System.Drawing.Size(96, 52);
            this.btnHall12.TabIndex = 11;
            this.btnHall12.Tag = 12;
            this.btnHall12.Text = "ПК 12";
            this.btnHall12.UseVisualStyleBackColor = false;
            this.lblSelectedComputer.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.lblSelectedComputer.Location = new System.Drawing.Point(3, 148);
            this.lblSelectedComputer.Name = "lblSelectedComputer";
            this.lblSelectedComputer.Size = new System.Drawing.Size(538, 32);
            this.lblSelectedComputer.TabIndex = 1;
            this.lblSelectedComputer.Text = "Выбран ПК 1";
            this.lblSelectedComputer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.actionsPanel.Controls.Add(this.btnStart);
            this.actionsPanel.Controls.Add(this.btnBooking);
            this.actionsPanel.Controls.Add(this.btnStartBooking);
            this.actionsPanel.Controls.Add(this.btnExtend);
            this.actionsPanel.Controls.Add(this.btnComplete);
            this.actionsPanel.Controls.Add(this.btnDeleteBooking);
            this.actionsPanel.Controls.Add(this.btnRefresh);
            this.actionsPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.actionsPanel.Location = new System.Drawing.Point(3, 192);
            this.actionsPanel.Name = "actionsPanel";
            this.actionsPanel.Size = new System.Drawing.Size(994, 64);
            this.actionsPanel.TabIndex = 2;
            this.btnStart.Location = new System.Drawing.Point(12, 18);
            this.btnStart.Name = "btnStart";
            this.btnStart.Size = new System.Drawing.Size(120, 34);
            this.btnStart.TabIndex = 0;
            this.btnStart.Text = "Открыть сеанс";
            this.btnStart.UseVisualStyleBackColor = true;
            this.btnStart.Click += new System.EventHandler(this.OnStartSessionClick);
            this.btnBooking.Location = new System.Drawing.Point(146, 18);
            this.btnBooking.Name = "btnBooking";
            this.btnBooking.Size = new System.Drawing.Size(120, 34);
            this.btnBooking.TabIndex = 1;
            this.btnBooking.Text = "Новая бронь";
            this.btnBooking.UseVisualStyleBackColor = true;
            this.btnBooking.Click += new System.EventHandler(this.OnCreateBookingClick);
            this.btnStartBooking.Location = new System.Drawing.Point(280, 18);
            this.btnStartBooking.Name = "btnStartBooking";
            this.btnStartBooking.Size = new System.Drawing.Size(140, 34);
            this.btnStartBooking.TabIndex = 2;
            this.btnStartBooking.Text = "Начать по брони";
            this.btnStartBooking.UseVisualStyleBackColor = true;
            this.btnStartBooking.Click += new System.EventHandler(this.OnStartByBookingClick);
            this.btnExtend.Location = new System.Drawing.Point(434, 18);
            this.btnExtend.Name = "btnExtend";
            this.btnExtend.Size = new System.Drawing.Size(100, 34);
            this.btnExtend.TabIndex = 3;
            this.btnExtend.Text = "Продлить";
            this.btnExtend.UseVisualStyleBackColor = true;
            this.btnExtend.Click += new System.EventHandler(this.OnExtendClick);
            this.btnComplete.Location = new System.Drawing.Point(548, 18);
            this.btnComplete.Name = "btnComplete";
            this.btnComplete.Size = new System.Drawing.Size(110, 34);
            this.btnComplete.TabIndex = 4;
            this.btnComplete.Text = "Завершить";
            this.btnComplete.UseVisualStyleBackColor = true;
            this.btnComplete.Click += new System.EventHandler(this.OnCompleteClick);
            this.btnDeleteBooking.Location = new System.Drawing.Point(672, 18);
            this.btnDeleteBooking.Name = "btnDeleteBooking";
            this.btnDeleteBooking.Size = new System.Drawing.Size(130, 34);
            this.btnDeleteBooking.TabIndex = 5;
            this.btnDeleteBooking.Text = "Отменить бронь";
            this.btnDeleteBooking.UseVisualStyleBackColor = true;
            this.btnDeleteBooking.Click += new System.EventHandler(this.OnDeleteBookingClick);
            this.btnRefresh.Location = new System.Drawing.Point(816, 18);
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.Size = new System.Drawing.Size(100, 34);
            this.btnRefresh.TabIndex = 6;
            this.btnRefresh.Text = "Обновить";
            this.btnRefresh.UseVisualStyleBackColor = true;
            this.btnRefresh.Click += new System.EventHandler(this.OnRefreshClick);
            this.sessionsGroup.Controls.Add(this.gridSessions);
            this.sessionsGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sessionsGroup.Location = new System.Drawing.Point(3, 262);
            this.sessionsGroup.Name = "sessionsGroup";
            this.sessionsGroup.Size = new System.Drawing.Size(444, 303);
            this.sessionsGroup.TabIndex = 3;
            this.sessionsGroup.TabStop = false;
            this.sessionsGroup.Text = "Активные сеансы";
            this.gridSessions.AllowUserToAddRows = false;
            this.gridSessions.AllowUserToDeleteRows = false;
            this.gridSessions.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.gridSessions.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gridSessions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridSessions.Location = new System.Drawing.Point(3, 21);
            this.gridSessions.MultiSelect = false;
            this.gridSessions.Name = "gridSessions";
            this.gridSessions.ReadOnly = true;
            this.gridSessions.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.gridSessions.Size = new System.Drawing.Size(438, 279);
            this.gridSessions.TabIndex = 0;
            this.bookingsGroup.Controls.Add(this.gridBookings);
            this.bookingsGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bookingsGroup.Location = new System.Drawing.Point(453, 262);
            this.bookingsGroup.Name = "bookingsGroup";
            this.bookingsGroup.Size = new System.Drawing.Size(544, 303);
            this.bookingsGroup.TabIndex = 4;
            this.bookingsGroup.TabStop = false;
            this.bookingsGroup.Text = "Брони";
            this.gridBookings.AllowUserToAddRows = false;
            this.gridBookings.AllowUserToDeleteRows = false;
            this.gridBookings.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.gridBookings.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gridBookings.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridBookings.Location = new System.Drawing.Point(3, 21);
            this.gridBookings.MultiSelect = false;
            this.gridBookings.Name = "gridBookings";
            this.gridBookings.ReadOnly = true;
            this.gridBookings.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.gridBookings.Size = new System.Drawing.Size(538, 279);
            this.gridBookings.TabIndex = 0;
            this.lblMessage.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.lblMessage.Location = new System.Drawing.Point(0, 568);
            this.lblMessage.Name = "lblMessage";
            this.lblMessage.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.lblMessage.Size = new System.Drawing.Size(1000, 32);
            this.lblMessage.TabIndex = 1;
            this.lblMessage.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 17F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.mainLayout);
            this.Controls.Add(this.lblMessage);
            this.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.Name = "SessionPage";
            this.Size = new System.Drawing.Size(1000, 600);
            this.mainLayout.ResumeLayout(false);
            this.clientPanel.ResumeLayout(false);
            this.clientPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridClients)).EndInit();
            this.hallGroup.ResumeLayout(false);
            this.hallPanel.ResumeLayout(false);
            this.actionsPanel.ResumeLayout(false);
            this.sessionsGroup.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.gridSessions)).EndInit();
            this.bookingsGroup.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.gridBookings)).EndInit();
            this.ResumeLayout(false);
        }
    }
}
